### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by CDNievas** [christiangiliberti/ejerciciosJSAsync#1]
Ojo que al hacer esto

```javascript
obtenerChiste().then(objeto=>console.log(objeto[0].setup));
obtenerChiste().then(objeto=>console.log(objeto[0].punchline));
```

Estas pidiendo dos veces el recurso chiste pudiendo haber impreso todo de una pidiendolo solo una vez...

**Comment by christiangiliberti** [comment]
Gracias por el feedback, ya esta corregido, Saludos!
